### PR TITLE
Support Laravel 7

### PR DESCRIPTION
**Pull request by andresayej**

### CODE REVIEW

**Comment by andresayej** [comment]
Yeah, sure I can do that, however I'm afraid that for that to work, the package has to drop support for Laravel ^5.5.

Are you okay with that?

**Comment by rasmuscnielsen** [comment]
It'd be great if we could keep 5.5 unless it's a big problem. 
I see you're working on it right now - we can drop collision if that makes it easier :-) I'd rather that than having yet another variable in the Travis config 👍

**Comment by andresayej** [comment]
Yeah, I am trying different things. It seems that the problem is the collision package. May I ask what is the initial reason it was added, before removing it?

**Comment by andresayej** [comment]
@rasmuscnielsen I need a little bit of help. I'm pretty confident that all is good however TravisCI is failing sometimes with a random pattern for different Laravel versions for no apparent reason.
Even more in previous builds, it has succeeded for the versions it is now failing. Very strange.

See these two examples:
https://travis-ci.org/makeabledk/laravel-factory-enhanced/builds/658632455?utm_source=github_status&utm_medium=notification

and

https://travis-ci.org/andresayej/laravel-factory-enhanced?utm_medium=notification&utm_source=github_status

**Comment by rasmuscnielsen** [comment]
Hey @andresayej 

Thank you so much for your contribution. It looks great now - the bug you're experiencing indeed seems random and completely unrelated to this. I believe I've seen it once or twice in the past, but have yet to figure out what causes it (contributions are indeed welcome).

The final thing I'd ask from you is if you could do a git rebase to a single commit which looks a bit nicer? Otherwise I can do a squash merge, but I'd prefer to make sure your contribution shows up in the history and gets credited properly with you as author :-) 

Cheers

**Comment by andresayej** [comment]
@rasmuscnielsen in my attempt to make this happen (git rebase to a single commit) I've accidentally deleted the remote-tracking branch...oops 😄.
Anyway, I've opened a new PR.

By the way, may I ask, how do you usually do this kind of git rebase to a single commit 
stuff, so I can properly do it next time if needed?

**Comment by rasmuscnielsen** [comment]
Hey @andresayej - no worries! 

For future reference checkout these two articles. 
https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d
https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

Basically you want to do something like `git rebase -i HEAD~5` and then squash all subsequent commits into the first "Bump to Laravel 7" :-) The articles should explain it fairly well 👍

**Comment by andresayej** [comment]
@rasmuscnielsen Thanks for the links, I've bookmarked them for future reference.
 
It seems I was halfway there, the squashing was successful, but I've missed this:
```
# Reapply it onto upstream's
git rebase 

# Fix conflicts, then `git rebase --continue`, repeat until done
# Push to our fork
git push --force 
```

Thank you and happy coding.

**Pull request closed without merging**
